php:
  build: ./
  container_name: apache-php-8.2
  ports:
  - 80:80
  - 8000:8000
  volumes: 
  - ./:/var/www/html
db:
  image: postgres:latest
  container_name: postgres
  ports:
  - 5432:5432
  environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fitness_food
